const URL="https://bflyuzgxhqdovrahycgg.supabase.co";const KEY="sb_publishable_GDOsyPod6iJuKWT1AWfgUQ_nvS-Z68V";const db=supabase.createClient(URL,KEY);const $=id=>document.getElementById(id);
const DB="arn-offline",STORE="queue";function idb(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id",autoIncrement:true});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function addQ(x){let d=await idb();return new Promise((ok,no)=>{let t=d.transaction(STORE,"readwrite");t.objectStore(STORE).add(x);t.oncomplete=ok;t.onerror=()=>no(t.error)})}
async function allQ(){let d=await idb();return new Promise((ok,no)=>{let r=d.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function delQ(id){let d=await idb();return new Promise((ok,no)=>{let t=d.transaction(STORE,"readwrite");t.objectStore(STORE).delete(id);t.oncomplete=ok})}
async function auth(){let s=await db.auth.getSession();if(s.data.session)return true;let r=await db.auth.signInAnonymously();return !r.error}
async function load(){let q=$("search").value.toLowerCase();let r=await db.from("v_inventory_stock").select("item_code,item_name,stock_current,current_status").order("item_code");if(r.error){$("inventory").textContent="Tidak bisa mengambil data online.";return}let a=r.data.filter(x=>!q||x.item_code.toLowerCase().includes(q)||x.item_name.toLowerCase().includes(q));$("inventory").innerHTML=a.map(x=>`<div class="item"><div class="top"><b>${x.item_code}</b><b>${x.stock_current??0}</b></div><div>${x.item_name}</div><small>${x.current_status||""}</small></div>`).join("")||"Tidak ada barang."}
async function sync(){if(!navigator.onLine||!(await auth()))return;for(const x of await allQ()){let r=await db.from("stock_movements").insert(x.data);if(!r.error)await delQ(x.id)}}
$("save").onclick=async()=>{let code=$("code").value.trim().toUpperCase(),qty=Number($("qty").value);if(!code||qty<1){$("msg").textContent="Isi kode dan jumlah.";return}let data={movement_code:"ARN-"+Date.now(),movement_date:new Date().toISOString().slice(0,10),item_code:code,movement_type:$("type").value,quantity:qty,note:$("note").value||null};try{if(!navigator.onLine||!(await auth()))throw 0;let r=await db.from("stock_movements").insert(data);if(r.error)throw r.error;$("msg").textContent="Tersimpan ke Supabase."}catch(e){await addQ({data});$("msg").textContent="Offline: transaksi disimpan di HP, nanti disinkronkan."}load()};
$("search").oninput=load;window.addEventListener("online",async()=>{ $("status").textContent="Online";await sync();load()});window.addEventListener("offline",()=>$("status").textContent="Offline");
(async()=>{$("status").textContent=navigator.onLine?"Online":"Offline";if(navigator.onLine)await auth();await sync();load();navigator.serviceWorker&&navigator.serviceWorker.register("sw.js")})();